# Generated by Django 4.1.6 on 2023-02-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='color',
            field=models.CharField(default='color1', help_text="вставьте 'color1' - зеленый\n2'color2' - аква\n2'color3' - оранжевый", max_length=6, verbose_name='цвета'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='name',
            field=models.CharField(max_length=55, verbose_name='тариф'),
        ),
    ]
