# Generated by Django 4.1.6 on 2023-02-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.DateField()),
                ('img', models.ImageField(upload_to='home/')),
                ('name', models.CharField(max_length=255, verbose_name='Название ')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
