# Generated by Django 4.1.6 on 2023-02-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.CharField(choices=[('Therd', 'Therd'), ('Others', 'Others')], default='Others', max_length=6, verbose_name='Тег'),
        ),
    ]
