# Generated by Django 4.1.6 on 2023-02-28 10:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
