# Generated by Django 4.1.6 on 2023-02-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posts_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Публикации'},
        ),
    ]
