# Generated by Django 4.1.6 on 2023-02-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ')),
            ],
            options={
                'verbose_name_plural': 'Категории портофолио',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='plan/')),
                ('name1', models.CharField(max_length=255, verbose_name='Название ')),
                ('desc1', models.TextField(verbose_name='Описание')),
                ('img2', models.ImageField(upload_to='plan/')),
                ('name2', models.CharField(max_length=255, verbose_name='Название ')),
                ('desc2', models.TextField(verbose_name='Описание')),
                ('img3', models.ImageField(upload_to='plan/')),
                ('name3', models.CharField(max_length=255, verbose_name='Название ')),
                ('desc3', models.TextField(verbose_name='Описание')),
                ('img4', models.ImageField(upload_to='plan/')),
                ('name4', models.CharField(max_length=255, verbose_name='Название ')),
                ('desc4', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'План',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.DateTimeField()),
                ('img', models.ImageField(upload_to='home/')),
                ('name', models.CharField(max_length=55, verbose_name='Название ')),
                ('desc_reviews', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='service/')),
                ('name', models.CharField(max_length=255, verbose_name='Название ')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Sett',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('google', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('vk', models.CharField(blank=True, max_length=255, null=True)),
                ('ok', models.CharField(blank=True, max_length=255, null=True)),
                ('ph_number', models.CharField(blank=True, max_length=13, null=True)),
                ('ph_number_support', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='home/')),
                ('name', models.CharField(max_length=255, verbose_name='Название ')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.categoryportfolio')),
            ],
            options={
                'verbose_name_plural': 'Портофолио',
            },
        ),
    ]
