# Generated by Django 4.1.6 on 2023-02-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('video_link', models.CharField(blank=True, max_length=255, null=True)),
                ('title_regular', models.CharField(max_length=55, verbose_name='текст 1 ')),
                ('title_bold', models.CharField(max_length=55, verbose_name='текст 2 ')),
                ('title_sing', models.CharField(max_length=55, verbose_name='текст 3 ')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterField(
            model_name='reviews',
            name='desc_reviews',
            field=models.TextField(verbose_name='Описание отзыва'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=55, verbose_name='ФИО'),
        ),
    ]
