# Generated by Django 4.1.6 on 2023-02-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_slider_alter_reviews_desc_reviews_alter_reviews_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Слайдер'},
        ),
    ]
